config/routes.rb
Jupiter::Application.routes.draw do 

  devise_for :admins

  mount Piggybak::Engine => '/checkout', :as => 'piggybak'
  devise_for :users

resources :deals
  get "landing_pages/home"
  get "landing_pages/product"
  get "landing_pages/about"
  get "landing_pages/recent"
  get "landing_pages/order"
  root :to => 'landing_pages#home'
  

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  attr_accessible :email, :password, :password_confirmation, :name, :remember_me
end

app/models/deal.rb
class Deal < ActiveRecord::Base
  scope :Object_sort, -> { order(:Object_Name)}
  scope :high_price, -> { where('price > ?', 500)}
  scope :med_price, -> { where('price >= ? AND price <= ?', 300, 500)}
  scope :low_price, -> { where('price < ?', 300)}
  belongs_to :User
  attr_accessible :Object_Name, :price, :User_id
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :count, :description, :name, :price, :piggybak_sellable_attributes
  acts_as_sellable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  attr_accessible :email, :name, :password, :password_confirmation, :remember_me

  validates :name, presence: true
  validates :password, length: {within: 6..12}
  emailFormatValidation = /[a-z.-]+@[a-z \d .-]+.[a-z]+/i
  validates :email, format: {with: emailFormatValidation}, uniqueness: true
  validates :password, confirmation: true
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
  def new
    @deal = Deal.new
    if !user_signed_in?
      redirect_to new_user_session_path
    end
  end

  def create
  	@deal = Deal.new(params[:deal])
	  if(@deal.User_id !=current_user.id)
      redirect_to root_path
    else
      if @deal.save
		    redirect_to deals_path
      else
		    render 'new'
      end
    end
  end

  def edit
    @deal = Deal.find(params[:id])
  end

  def update
    @deal = Deal.find(params[:id])
    if @deal.update_attributes(params[:deal])
      redirect_to deals_path
    else
      render 'edit'
    end
  end

  def index
    @deal = Deal.new
    if user_signed_in?
      @deals_high = Deal.high_price
      @deals_med = Deal.med_price
      @deals_low = Deal.low_price
      @deals = Deal.all
    else
      redirect_to new_user_session_path
    end
  end

  def destroy
    @deal = Deal.find(params[:id])
    @deal.destroy
    redirect_to deals_path
  end
  
  def show
      @deal = Deal.find(params[:id])
  end
end

app/controllers/landing_pages_controller.rb
class LandingPagesController < ApplicationController
  def home
  	if !user_signed_in?
  		redirect_to new_user_registration_path
  	else
  		redirect_to landing_pages_about_path
  	end
  end
  
  def product
  end
  
  def about
  end

  def recent
  end

  def order
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/deals/edit.html.erb
<%= form_for(@deal) do |f| %>	
	<div class="field">
		<p>Object Name</p>
		<%= f.text_field :Object_Name%>
	</div>
	
	<div class="field">
		<p>Price</p>
		<%= f.text_field :price %>
	</div>
	
	<div class="field">
		<p>User</p>
		<%= f.collection_select :User_id, User.all, :id, :name %>
	</div>

	<div class="field">
		<%= f.hidden_field :User_id, :value => current_user.id%>
	</div>

	<div class="actions">
		<%= f.submit %>
	</div>
<% end %>

app/views/deals/index.html.erb
<body>
<table>
	<tr>
		<td style="font-size:20px; position:relative; left: 5%; text-decoration: underline">Deal<span class="Deals"></span></td>
		<td style="font-size:20px; position:relative; left: 25%; text-decoration: underline">Price($)</td>
		<td style="font-size:20px; position:relative; left: 45%; text-decoration: underline">User</td>
	</tr>

<% @deals_high.each do |deal| %>
	<tr class="dpu">
		<td class="high" style="position:relative; left: 5%"><%= deal.Object_Name %></td>
		<td class="high" style="position:relative; left: 25%"><%= deal.price %></td>
		<td class="high" style="position:relative; left: 45%"><%= deal.User.name %></td>
		<td style="position:relative; left: 60%"><%= button_to "show deal",deal_path(deal.id), method: :get %></td>
		<td style="position:relative; left: 70%"><%= button_to "edit deal", edit_deal_path(deal.id), method: :get %></td>
		<td style="position:relative; left: 80%"><%= button_to "delete deal", deal, confirm: "You are about to delete this deal. Would you like to continue?", method: :delete %></td>
	</tr>
<% end %>

<% @deals_med.each do |deal| %>
	<tr class="dpu">
		<td class="med" style="position:relative; left: 5%"><%= deal.Object_Name %></td>
		<td class="med" style="position:relative; left: 25%"><%= deal.price %></td>
		<td class="med" style="position:relative; left: 45%"><%= deal.User.name %></td>
		<td style="position:relative; left: 60%"><%= button_to "show deal", deal_path(deal.id), method: :get %></td>
		<td style="position:relative; left: 70%"><%= button_to "edit deal", edit_deal_path(deal.id), method: :get %></td>
		<td style="position:relative; left: 80%"><%= button_to "delete deal", deal, confirm: "You are about to delete this deal. Would you like to continue?", method: :delete %></td>
	</tr>
<% end %>

<% @deals_low.each do |deal| %>
	<tr class="dpu">
		<td class="low" style="position:relative; left: 5%"><%= deal.Object_Name %></td>
		<td class="low" style="position:relative; left: 25%"><%= deal.price %></td>
		<td class="low" style="position:relative; left: 45%"><%= deal.User.name %></td>
		<td style="position:relative; left: 60%"><%= button_to "show deal", deal_path(deal.id), method: :get %></td>
		<td style="position:relative; left: 70%"><%= button_to "edit deal", edit_deal_path(deal.id), method: :get %></td>
		<td style="position:relative; left: 80%"><%= button_to "delete deal", deal, confirm: "You are about to delete this deal. Would you like to continue?", method: :delete %></td>
	</tr>
<% end %>
</table>
</body>

app/views/deals/new.html.erb
<%= form_for(@deal) do |f| %>
	<div class="field">
		<p>Object Name</p>
		<%= f.text_field :Object_Name %>
	</div>

	<div class="field">
		<p>Price</p>
		<%= f.text_field :price %>
	</div>

	<div class="field">
		<%= f.hidden_field :User_id, :value => current_user.id%>
	</div>

	<div class="actions">
		<%= f.submit %>
	</div>
<% end %>

app/views/deals/show.html.erb
<div>
	<h2><%= @deal.Object_Name %></h2>
	<p><%= @deal.price %></p>
	<p><%= @deal.User.name %></p>
</div>

app/views/landing_pages/about.html.erb
<!doctype html>
<html lang="zh-CN">

<div class="panel-group" id="accordion">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a class="btn-danger btn" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" id="button2">
          潘习安  
        </a>
      </h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse in">
      <div class="panel-body">
          潘习安来自美国，在UPenn（宾大）毕业，在北京大学，北京语言大学中文了。习安住在北京时爱上中国和他的中国兄弟姐妹。毕业之后，习安决定帮中国得到世界上第一发展的国家，创业了DTC。
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a class="btn-danger btn" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" id="button2">
          张大庆
        </a>
      </h4>
    </div>
    <div id="collapseTwo" class="panel-collapse collapse">
      <div class="panel-body">
          张大庆来自中国的湖北省，在中国石油工作了二十年。潘习安和张大庆在大庆家一起住了一年。这个时间之内，潘习安成为了大庆非正式的养子，张大庆鼓励潘习安开DTC。
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a class="btn-danger btn" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" id="button2">
          DTC 集团
        </a>
      </h4>
    </div>
    <div id="collapseThree" class="panel-collapse collapse">
      <div class="panel-body">
          张大庆和潘习安发现了在一起可以帮中人国采用世界上最新的产品，帮中国成为世界第一强的国家。几个月之后，他们创业了DTC。
      </div>
    </div>
  </div>
</div>

<br />

<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>

      <div class="carousel-inner">
        <div class="item active">
          <img class="carpics" src="../../assets/LinkedIn.png">
          <div class="container">
            <div class="carousel-caption">
              <h1>Shane Prebenda</h1>
              <p class="lead">Shane Prebenda founded DTC in December 2013.</p>
            </div>
          </div>
        </div>
        <div class="item">
          <img class="carpics" src="../../assets/Audi_Interior.jpg">
          <div class="container">
            <div class="carousel-caption">
              <h1>Zhang Da Qing</h1>
              <p class="lead">Zhang Da Qing is responsible for the inspiration behind DTC.</p>
            </div>
          </div>
        </div>
        <div class="item">
          <img class="carpics" src="../../assets/GlobalConnectedness.jpg">
          <div class="container">
            <div class="carousel-caption">
              <h1>Connected</h1>
              <p class="lead">In today's world, staying connected is extremely important.</p>
            </div>
          </div>
        </div>
      </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
  </a>
</div>

app/views/landing_pages/order.html.erb
<p> Coming Soon! </p>

app/views/landing_pages/product.html.erb
<!doctype html>
<html lang="zh-CN">

<div class="panel-group" id="accordion">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a class="btn-primary btn" data-toggle="collapse" data-parent="#accordion" href="#collapse1"id="button3">
          D500  
        </a>
      </h4>
    </div>
    <div id="collapse1" class="panel-collapse collapse in">
      <div class="panel-body">
          The D500 is our latest model. It has a x horsepower engine...
      </div>
      <img src="../../assets/Audi_Interior.jpg" />
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a class="btn-primary btn" data-toggle="collapse" data-parent="#accordion" href="#collapse2"id="button3">
          D1000
        </a>
      </h4>
    </div>
    <div id="collapse2" class="panel-collapse collapse">
      <div class="panel-body">
          The D1000 is our most popular model. It has a y horsepower engine...
      </div>
      <img src="../../assets/Audi_Interior.jpg" />
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a class="btn-primary btn" data-toggle="collapse" data-parent="#accordion" href="#collapse3"id="button3">
          D1500
        </a>
      </h4>
    </div>
    <div id="collapse3" class="panel-collapse collapse">
      <div class="panel-body">
          The D1500 is our largest, most powerful model. It has a z horsepower engine...
      </div>
      <img src="../../assets/Audi_Interior.jpg" />
    </div>
  </div>
</div>

app/views/landing_pages/recent.html.erb
<h2 id="RecentHeading">Recent Activity</h2>

<br />
<br />
<p> DTC is preparing to launch in China on February 6, 2014 after the Chinese New Year. Until that time, DTC executives will be working around the clock to expand the products, services and functionalities provided by this site.</p>
<br />
<p> We encourage our visitors to read our "About Us" page, make an account to access the deals portion of the site, and engage in the services our site has to offer at this time. Happy viewing!</p>
<br />
<p>--The DTC Team </p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DTC</title>
  <link rel="stylesheet" type="text/css" ref="../assets/bootstrap.css">
  <script src="../assets/bootstrap.js"></script>
<%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>          
  <% if "#{params[:controller]}##{params[:action]}" == "piggybak/orders#submit" -%>
      <%= javascript_include_tag "piggybak/piggybak-application" %>
  <% end -%>

  <%= csrf_meta_tags %>

</head>
<body>

<nav class="navbar navbar-default; wrapperHeader" role="navigation">
	<!-- Brand and toggle get grouped for better mobile display -->
	<div id="navbar-header">
		<% if user_signed_in? %>
		<div id="navtit"><p class="navbar-brand">
			<a id="dtc" href=<%=deals_path %>>DTC</a>
		</p></div>
		<% else %>
		<p class="navbar-brand">
			<a id="dtc"href=<%=root_path %>>DTC</a>
		</p>
		<% end %>
	</div>

	<ul class="nav navbar-nav">
		<% if user_signed_in? %>
		<li class="dropdown">
			<a href="#" class="dropdown-toggle" data-toggle="dropdown">Deals<b class="caret"></b></a>
			<ul class="dropdown-menu">
				<li><%= link_to "New Deal", new_deal_path %></li>
				<li><%= link_to "Current Deals", deals_path %></li>
			</ul>
		</li>
		<% end %>
		<li>
			<%= link_to "Recent Activity", landing_pages_recent_path %>
		</li>
		<li>
			<%= link_to "Our Products", landing_pages_product_path %>
		</li>
		<li>
			<%= link_to "About Us", landing_pages_about_path %>
		</li>
		<li>
			<%= link_to "Order Here!", landing_pages_order_path %>
		</li>
	</ul>

	<ul class="nav navbar-nav" style="position: absolute; right: 20px">
		<% if user_signed_in? %>
		<li>
			<%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
		</li>
		<% else %>
		<li>
			<div class="navbar-inner">
			<%= form_for(resource, :as => resource_name, :url => session_path(resource_name), html: {class:"navbar-search pull-right"}) do |f| %>
			
				<%= f.email_field :email, :autofocus => true, html: {class: "span2"},  placeholder: "email" %>
			
					<%= f.password_field :password, html: {class: "span2"}, placeholder: "password" %></div>

					<% if devise_mapping.rememberable? -%>
					<%= f.check_box :remember_me %> <%= f.label :remember_me %>
					<% end %>

					<%= f.submit "Sign in", html: {class: "pull-right span1"} %>
					<% end %>
			</div>
		</li>
		<% end %>
	</ul>
 		<!--<div class='navbar-inner'>
			<form class="navbar-search pull-right">
            	<input type="text" class="span2" placeholder="Login">
            	<input type="text" class="span2" placeholder="Password">
            	<input type="submit" value="Login" class="btn"/>
       		</form>
  		</div>-->
</nav>

<p class="notice"><%=notice %></p>
<p class="alert"><%=alert %></p>

<%= yield %>

<script>
  $('.dropdown-toggle').dropdown();
</script>

<div id="footer">
</div>

</body>
</html>